package org.wahlen.voucherengine.persistence.model.customer

import jakarta.persistence.Column
import jakarta.persistence.Embeddable

/**
 * Embeddable asset references for Voucherengine vouchers such as QR and barcode images.
 *
 * These assets are generated by Voucherengine for use in wallet passes, POS scanning,
 * or customer-facing voucher delivery.
 *
 * Voucherengine API Docs: Vouchers.
 */
@Embeddable
class AddressEmbeddable(

    /**
     * City
     */
    @Column
    var city: String? = null,

    /**
     * State
     */
    @Column(columnDefinition = "TEXT")
    var state: String? = null,

    /**
     * First line of address
     */
    @Column
    var line_1: String? = null,

    /**
     * Second line of address
     */
    @Column
    var line_2: String? = null,

    /**
     * Country
     */
    @Column
    var country: String? = null,

    /**
     * Postal code
     */
    @Column(columnDefinition = "TEXT")
    var postalCode: String? = null
)
