import authenticate.http

### obtain the access_token
run #authenticate_tenant

### Use the token in a follow-up request (example)
GET {{keycloak_base_url}}/realms/{{realm}}/.well-known/openid-configuration
Authorization: Bearer {{tenant_access_token}}
