package org.wahlen.voucherengine.persistence.model.voucher

import jakarta.persistence.Column
import jakarta.persistence.Embeddable

/**
 * Embeddable asset references for Voucherengine vouchers such as QR and barcode images.
 *
 * These assets are generated by Voucherengine for use in wallet passes, POS scanning,
 * or customer-facing voucher delivery.
 *
 * Voucherengine API Docs: Vouchers.
 */
@Embeddable
class VoucherAssetsEmbeddable(
    @Column
    var qrId: String? = null,

    @Column(columnDefinition = "TEXT")
    var qrUrl: String? = null,

    @Column
    var barcodeId: String? = null,

    @Column(columnDefinition = "TEXT")
    var barcodeUrl: String? = null
)
