package org.wahlen.voucherengine.persistence.model.validation

/**
 * Enumerates validation rule context types defined by Voucherengine.
 *
 * Voucherengine API Docs: Validation Rules.
 */
enum class ValidationRuleContextType(val value: String) {
    EARNING_RULE_ORDER_PAID("earning_rule.order.paid"),
    EARNING_RULE_CUSTOM_EVENT("earning_rule.custom_event"),
    EARNING_RULE_CUSTOMER_SEGMENT_ENTERED("earning_rule.customer.segment.entered"),
    EARNING_RULE_CUSTOMER_TIER_JOINED("earning_rule.customer.tier.joined"),
    EARNING_RULE_CUSTOMER_TIER_LEFT("earning_rule.customer.tier.left"),
    EARNING_RULE_CUSTOMER_TIER_UPGRADED("earning_rule.customer.tier.upgraded"),
    EARNING_RULE_CUSTOMER_TIER_DOWNGRADED("earning_rule.customer.tier.downgraded"),
    EARNING_RULE_CUSTOMER_TIER_PROLONGED("earning_rule.customer.tier.prolonged"),
    CAMPAIGN_DISCOUNT_COUPONS("campaign.discount_coupons"),
    CAMPAIGN_DISCOUNT_COUPONS_DISCOUNT_APPLY_TO_ORDER("campaign.discount_coupons.discount.apply_to_order"),
    CAMPAIGN_DISCOUNT_COUPONS_DISCOUNT_APPLY_TO_ITEMS("campaign.discount_coupons.discount.apply_to_items"),
    CAMPAIGN_DISCOUNT_COUPONS_DISCOUNT_APPLY_TO_ITEMS_PROPORTIONALLY(
        "campaign.discount_coupons.discount.apply_to_items_proportionally"
    ),
    CAMPAIGN_DISCOUNT_COUPONS_DISCOUNT_APPLY_TO_ITEMS_PROPORTIONALLY_BY_QUANTITY(
        "campaign.discount_coupons.discount.apply_to_items_proportionally_by_quantity"
    ),
    CAMPAIGN_DISCOUNT_COUPONS_DISCOUNT_APPLY_TO_ITEMS_BY_QUANTITY(
        "campaign.discount_coupons.discount.apply_to_items_by_quantity"
    ),
    CAMPAIGN_DISCOUNT_COUPONS_DISCOUNT_FIXED_APPLY_TO_ITEMS("campaign.discount_coupons.discount.fixed.apply_to_items"),
    CAMPAIGN_DISCOUNT_COUPONS_DISCOUNT_PERCENT_APPLY_TO_ITEMS("campaign.discount_coupons.discount.percent.apply_to_items"),
    CAMPAIGN_GIFT_VOUCHERS("campaign.gift_vouchers"),
    CAMPAIGN_GIFT_VOUCHERS_GIFT_APPLY_TO_ORDER("campaign.gift_vouchers.gift.apply_to_order"),
    CAMPAIGN_GIFT_VOUCHERS_GIFT_APPLY_TO_ITEMS("campaign.gift_vouchers.gift.apply_to_items"),
    CAMPAIGN_REFERRAL_PROGRAM("campaign.referral_program"),
    CAMPAIGN_REFERRAL_PROGRAM_DISCOUNT_APPLY_TO_ORDER("campaign.referral_program.discount.apply_to_order"),
    CAMPAIGN_REFERRAL_PROGRAM_DISCOUNT_APPLY_TO_ITEMS("campaign.referral_program.discount.apply_to_items"),
    CAMPAIGN_REFERRAL_PROGRAM_DISCOUNT_APPLY_TO_ITEMS_PROPORTIONALLY(
        "campaign.referral_program.discount.apply_to_items_proportionally"
    ),
    CAMPAIGN_REFERRAL_PROGRAM_DISCOUNT_APPLY_TO_ITEMS_PROPORTIONALLY_BY_QUANTITY(
        "campaign.referral_program.discount.apply_to_items_proportionally_by_quantity"
    ),
    CAMPAIGN_REFERRAL_PROGRAM_DISCOUNT_APPLY_TO_ITEMS_BY_QUANTITY(
        "campaign.referral_program.discount.apply_to_items_by_quantity"
    ),
    CAMPAIGN_REFERRAL_PROGRAM_DISCOUNT_FIXED_APPLY_TO_ITEMS("campaign.referral_program.discount.fixed.apply_to_items"),
    CAMPAIGN_REFERRAL_PROGRAM_DISCOUNT_PERCENT_APPLY_TO_ITEMS("campaign.referral_program.discount.percent.apply_to_items"),
    CAMPAIGN_PROMOTION("campaign.promotion"),
    CAMPAIGN_PROMOTION_DISCOUNT_APPLY_TO_ORDER("campaign.promotion.discount.apply_to_order"),
    CAMPAIGN_PROMOTION_DISCOUNT_APPLY_TO_ITEMS("campaign.promotion.discount.apply_to_items"),
    CAMPAIGN_PROMOTION_DISCOUNT_APPLY_TO_ITEMS_PROPORTIONALLY(
        "campaign.promotion.discount.apply_to_items_proportionally"
    ),
    CAMPAIGN_PROMOTION_DISCOUNT_APPLY_TO_ITEMS_PROPORTIONALLY_BY_QUANTITY(
        "campaign.promotion.discount.apply_to_items_proportionally_by_quantity"
    ),
    CAMPAIGN_PROMOTION_DISCOUNT_APPLY_TO_ITEMS_BY_QUANTITY("campaign.promotion.discount.apply_to_items_by_quantity"),
    CAMPAIGN_PROMOTION_DISCOUNT_FIXED_APPLY_TO_ITEMS("campaign.promotion.discount.fixed.apply_to_items"),
    CAMPAIGN_PROMOTION_DISCOUNT_PERCENT_APPLY_TO_ITEMS("campaign.promotion.discount.percent.apply_to_items"),
    CAMPAIGN_LOYALTY_PROGRAM("campaign.loyalty_program"),
    VOUCHER_DISCOUNT_VOUCHER("voucher.discount_voucher"),
    VOUCHER_DISCOUNT_VOUCHER_DISCOUNT_APPLY_TO_ORDER("voucher.discount_voucher.discount.apply_to_order"),
    VOUCHER_DISCOUNT_VOUCHER_DISCOUNT_APPLY_TO_ITEMS("voucher.discount_voucher.discount.apply_to_items"),
    VOUCHER_DISCOUNT_VOUCHER_DISCOUNT_APPLY_TO_ITEMS_PROPORTIONALLY(
        "voucher.discount_voucher.discount.apply_to_items_proportionally"
    ),
    VOUCHER_DISCOUNT_VOUCHER_DISCOUNT_APPLY_TO_ITEMS_PROPORTIONALLY_BY_QUANTITY(
        "voucher.discount_voucher.discount.apply_to_items_proportionally_by_quantity"
    ),
    VOUCHER_DISCOUNT_VOUCHER_DISCOUNT_APPLY_TO_ITEMS_BY_QUANTITY(
        "voucher.discount_voucher.discount.apply_to_items_by_quantity"
    ),
    VOUCHER_DISCOUNT_VOUCHER_DISCOUNT_FIXED_APPLY_TO_ITEMS("voucher.discount_voucher.discount.fixed.apply_to_items"),
    VOUCHER_DISCOUNT_VOUCHER_DISCOUNT_PERCENT_APPLY_TO_ITEMS("voucher.discount_voucher.discount.percent.apply_to_items"),
    VOUCHER_GIFT_VOUCHER("voucher.gift_voucher"),
    VOUCHER_GIFT_VOUCHER_GIFT_APPLY_TO_ORDER("voucher.gift_voucher.gift.apply_to_order"),
    VOUCHER_GIFT_VOUCHER_GIFT_APPLY_TO_ITEMS("voucher.gift_voucher.gift.apply_to_items"),
    VOUCHER_LOYALTY_CARD("voucher.loyalty_card"),
    DISTRIBUTION_CUSTOM_EVENT("distribution.custom_event"),
    DISTRIBUTION_ORDER_PAID("distribution.order.paid"),
    DISTRIBUTION_ORDER_CREATED("distribution.order.created"),
    DISTRIBUTION_ORDER_CANCELED("distribution.order.canceled"),
    DISTRIBUTION_ORDER_UPDATED("distribution.order.updated"),
    REWARD_ASSIGNMENT_PAY_WITH_POINTS("reward_assignment.pay_with_points"),
    GLOBAL("global");
}
