package org.wahlen.voucherengine.persistence.model.async

enum class AsyncJobType {
    BULK_VOUCHER_UPDATE,
    VOUCHER_METADATA_UPDATE,
    VOUCHER_IMPORT,
    VOUCHER_EXPORT,
    REDEMPTION_EXPORT,
    PUBLICATION_EXPORT,
    CUSTOMER_EXPORT,
    PRODUCT_EXPORT,
    SKU_EXPORT,
    TRANSACTION_EXPORT,
    CAMPAIGN_VOUCHER_GENERATION,
    ORDER_IMPORT,
    ORDER_EXPORT
}
